# Generated by Django 2.0.3 on 2020-08-04 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Hlat', models.FloatField(default=27.9, null=True)),
                ('Hlong', models.FloatField(default=89.5, null=True)),
                ('MaxSusWind', models.FloatField(default=160, null=True)),
                ('Clat', models.FloatField(default=29.951065, null=True)),
                ('Clong', models.FloatField(default=-90.071533, null=True)),
                ('Pop', models.FloatField(default=445000, null=True)),
                ('Area', models.FloatField(default=350, null=True)),
                ('prediction', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.CharField(max_length=1000)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location')),
            ],
        ),
    ]
